// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZr12Cl4N44pARnrCuBSd25a7pb5pdeAg',
    appId: '1:245851405688:web:8ae06c44495becdfc69c8d',
    messagingSenderId: '245851405688',
    projectId: 'todoapp-207f1',
    authDomain: 'todoapp-207f1.firebaseapp.com',
    storageBucket: 'todoapp-207f1.appspot.com',
    measurementId: 'G-GJN2NZJY74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4I3xIwA5Vl_qqt_vgQTlom956ECpdTgg',
    appId: '1:245851405688:android:17534016d8c71b01c69c8d',
    messagingSenderId: '245851405688',
    projectId: 'todoapp-207f1',
    storageBucket: 'todoapp-207f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiUE8lHKpOqg3IyDW-BJe030IrZlU0Wqk',
    appId: '1:245851405688:ios:1bb83d8c2ceb7377c69c8d',
    messagingSenderId: '245851405688',
    projectId: 'todoapp-207f1',
    storageBucket: 'todoapp-207f1.appspot.com',
    iosClientId: '245851405688-00g82236d86pckr3f7o2b1uf8qqempul.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiUE8lHKpOqg3IyDW-BJe030IrZlU0Wqk',
    appId: '1:245851405688:ios:1bb83d8c2ceb7377c69c8d',
    messagingSenderId: '245851405688',
    projectId: 'todoapp-207f1',
    storageBucket: 'todoapp-207f1.appspot.com',
    iosClientId: '245851405688-00g82236d86pckr3f7o2b1uf8qqempul.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZr12Cl4N44pARnrCuBSd25a7pb5pdeAg',
    appId: '1:245851405688:web:9bfda510dc050590c69c8d',
    messagingSenderId: '245851405688',
    projectId: 'todoapp-207f1',
    authDomain: 'todoapp-207f1.firebaseapp.com',
    storageBucket: 'todoapp-207f1.appspot.com',
    measurementId: 'G-BBJYWM7T9R',
  );

}
